#!/bin/bash

# Script local para construir el paquete .pkg.tar.zst de Arch Linux de AppInstall

# Asegurar que estamos en el directorio raíz del proyecto
cd "$(dirname "$0")"

# Primero construir el .deb para asegurar que toda la estructura usr/ en appinstall/ está al día y con los permisos correctos
./build_deb.sh

# Nombre del paquete y versión (extraídos del archivo control)
PACKAGE_NAME=$(grep '^Package:' appinstall/DEBIAN/control | cut -d' ' -f2)
VERSION=$(grep '^Version:' appinstall/DEBIAN/control | cut -d' ' -f2)

ARCH_PKG_NAME="${PACKAGE_NAME}-${VERSION}-1-any.pkg.tar.zst"

echo "Construyendo $ARCH_PKG_NAME..."

# Crear el directorio temporal para el paquete Arch
mkdir -p archpkg/
cp -r appinstall/usr/ archpkg/

# Calcular el tamaño de la carpeta en bytes y obtener la fecha de compilación
SIZE=$(du -sb archpkg/usr | cut -f1)
BUILDDATE=$(date +%s)

# Escribir el archivo de metadatos PKGINFO para el gestor de paquetes pacman de Arch
printf "%s\n" \
  "# Generated by build_arch.sh" \
  "pkgname = ${PACKAGE_NAME}" \
  "pkgver = ${VERSION}-1" \
  "pkgdesc = Simple package installer for Linux" \
  "url = https://github.com/InledGroup/appinstall" \
  "builddate = ${BUILDDATE}" \
  "packager = Jaime Gonzalez Herraiz <CONTACTO@INLED.ES>" \
  "size = ${SIZE}" \
  "arch = any" \
  "license = GPL3" \
  "depend = python" \
  "depend = python-gobject" \
  "depend = gtk4" \
  "depend = libadwaita" \
  "depend = python-requests" \
  "depend = python-packaging" \
  "depend = polkit" > archpkg/.PKGINFO

# Construir el archivo .pkg.tar.zst con tar y zstd
if command -v tar >/dev/null && command -v zstd >/dev/null; then
    cd archpkg
    tar --owner=0 --group=0 -cf - .PKGINFO usr | zstd -z -19 > "../${ARCH_PKG_NAME}"
    cd ..
    echo "¡Hecho! El paquete de Arch Linux se ha creado: $ARCH_PKG_NAME"
    # Limpiar
    rm -rf archpkg
else
    echo "Error: 'tar' o 'zstd' no están instalados. No puedo construir el paquete."
    exit 1
fi
